import pyautogui as aut 
# Faça o código 
aut.hotkey('win')
# Colocando as variaveis e etc... 
aut.write('chrome', interval=0.1)
aut.sleep(1)
aut.press('Enter')
aut.sleep(0.7)
# Faça com  que a programação de Enter
aut.write('https://classroom.google.com/c/NzAwNTU0Njc2MzY3')
aut.sleep(3)
aut.press('Enter')
aut.moveTo(1225,619)
aut.sleep(3)
aut.click()
aut.moveTo(1514,250)
aut.sleep(3)
aut.click()
aut.moveTo(964,562)
aut.sleep(3)
aut.click()
aut.hotkey('win')
aut.write('Explorador de Arquivos', interval=0.1)
aut.press('Enter')
aut.moveTo(106,311)
aut.sleep(3)
aut.click()
aut.moveTo(485,195)
aut.sleep(3)
aut.click()
aut.hotkey('ctlr','x')
aut.moveTo(91,280)
aut.sleep(3)
aut.click()
aut.moveTo(307,172)
aut.sleep(3)
aut.click()
aut.press('Enter')
aut.sleep(3)
aut.hotkey('ctrl','v')